import { portfolio as p } from "@/data/portfolio";
import { Header } from "@/components/header";
import { SectionHeading } from "@/components/section-heading";
export default function Home() {
    return <><a href="#main" className="skip-link">跳到主要内容</a><Header /><main id="main">
    <section id="home" className="hero container"><div className="hero-copy"><p className="availability"><span />{p.status}</p><p className="eyebrow hero-label">HELLO, NICE TO MEET YOU</p><h1>{p.title.split("，")[0]}，<br /><span>{p.title.split("，")[1]}</span></h1><p className="hero-role">{p.subtitle}</p><p className="hero-intro">{p.intro}</p><div className="actions"><a className="button primary" href="#projects">探索我的项目 <span>↗</span></a><a className="button secondary" href="/resume">查看与下载简历 <span>↓</span></a></div><p className="hero-location"><span>⌖</span> {p.location} <span className="divider">/</span> 期待下一段职业旅程</p></div><div className="hero-art" aria-label="连接、协作与执行的抽象图形"><div className="art-top"><span>IDEAS INTO IMPACT</span><span>↗</span></div><div className="art-grid"><div className="shape shape-one"/><div className="shape shape-two"/><div className="shape shape-three"/><div className="shape shape-four"/></div><div className="art-bottom"><span>连接 · 推进 · 创造价值</span><span>01 — 03</span></div><div className="art-note">有想法，也有行动。</div></div></section>
    <div className="container"><div className="principles">{p.stats.map(stat => <div key={stat.value}><span className="stat-number">{stat.value}</span><div><h3>{stat.label}</h3><p>{stat.note}</p></div><span className="stat-arrow">↗</span></div>)}</div><p className="placeholder-note">{p.note}</p></div>
    <section id="about" className="section container"><SectionHeading number="01" english="ABOUT ME" title="务实做事，认真合作。"/><div className="about-grid"><p className="large-copy">在业务与人之间，<br />做那个推动事情向前的人。</p><div><p className="body-copy">{p.about}</p><div className="tags">{p.values.map(value => <span key={value}>{value}</span>)}</div></div></div></section>
    <section id="experience" className="section container"><SectionHeading number="02" english="EXPERIENCE" title="每一段经历，都有积累。" description="在实际业务中学习，在具体任务中成长。"/><div className="timeline">{p.jobs.map((job, i) => <article className="job" key={i}><div className="job-date"><span className="timeline-dot"/>{job.period}<small>经历示例 · 待替换</small></div><div><h3>{job.role}</h3><p className="company">{job.company}</p><ul>{job.points.map(point => <li key={point}>{point}</li>)}</ul></div></article>)}</div></section>
    <section id="projects" className="section project-section"><div className="container"><SectionHeading number="03" english="SELECTED PROJECTS" title="用项目，讲述我的工作。" description="从业务问题出发，让过程可见，让结果有据。"/><div className="projects">{p.projects.map((project, i) => <article className="project-card" key={project.id}><div className={`project-visual visual-${i}`} aria-hidden="true"><span className="visual-caption">{project.category.toUpperCase()} / 0{i + 1}</span>{i === 0 ? <div className="partner-diagram"><span>伙伴</span><b>↔</b><span>业务</span></div> : i === 1 ? <div className="campaign-art"><span>MAKE<br />IT HAPPEN<span className="campaign-arrow">↗</span></span></div> : <div className="chart-art">{[35, 52, 45, 72, 90].map((v, n) => <span key={n} style={{ height: `${v}%` }}/>)}</div>}<span className="visual-bottom">{project.artifact}</span></div><div className="project-content"><p className="eyebrow">CASE STUDY / 0{i + 1}</p><h3>{project.title}</h3><p>{project.summary}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><details><summary>查看项目详情 <span>＋</span></summary><div className="case-detail"><h4>我的角色</h4><p>{project.role}</p><h4>业务挑战</h4><p>{project.challenge}</p><h4>关键行动</h4><p>{project.action}</p><h4>成果与验证</h4><p>{project.result}</p></div></details></div></article>)}</div></div></section>
    <section id="skills" className="section container"><SectionHeading number="04" english="CAPABILITIES" title="把能力，落实到工作里。"/><div className="skills-grid">{p.skills.map((skill, i) => <article key={skill.title}><span className="skill-icon">{["◎", "▧", "↗", "▤"][i]}</span><h3>{skill.title}</h3><p>{skill.text}</p><small>{skill.tools}</small></article>)}</div></section>
    <section id="work" className="section container"><SectionHeading number="05" english="WORK COLLECTION" title="不止经历，还有工作沉淀。" description="方案、手册与报告，记录思考如何变成行动。"/><div className="work-list">{p.projects.map((project, i) => <details key={project.id}><summary><span className="work-number">0{i + 1}</span><div><h3>{project.artifact}</h3><p>{project.category} · 示例作品结构</p></div><span className="work-type">{["PLAYBOOK", "PROPOSAL", "REPORT"][i]}</span><span className="work-open">＋</span></summary><div className="work-detail"><p>{project.summary}</p><p>作品内容框架：项目背景 → 目标与策略 → 执行过程 → 成果与复盘。</p><p className="placeholder-note">真实作品文件待提供。当前展示框架，不包含实际工作成果。</p></div></details>)}</div></section>
    <section id="education" className="section container"><SectionHeading number="06" english="EDUCATION" title="成长的起点。"/><div className="education"><span className="education-icon">▥</span><div><h3>{p.education.school}</h3><p>{p.education.major}</p><p className="muted">{p.education.detail}</p></div><span>{p.education.period}</span></div></section>
    <section id="contact" className="contact-section"><div className="container"><p className="eyebrow">07 / LET’S CONNECT</p><div className="contact-top"><h2>下一段旅程，<br />期待与你一起开启。<span>↗</span></h2><div><p>如果你正在寻找一位积极、可靠、<br />愿意深入业务的合作伙伴，欢迎联系我。</p><a className="button light" href={`mailto:${p.email}`}>发送邮件 <span>↗</span></a></div></div><div className="contact-bottom"><div><small>EMAIL</small><a href={`mailto:${p.email}`}>{p.email}</a></div><div><small>电话 / 微信</small><span>{p.phone} / {p.wechat}</span></div><a className="resume-link" href="/resume">查看与下载简历 ↓</a></div></div></section>
  </main><footer className="container footer"><span>© {p.copyrightYear} {p.name} · Personal Portfolio</span><span>认真做事，持续成长。</span><a href="#home">回到顶部 ↑</a></footer></>;
}
